// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Suruga.DSharpPlus.Handlers.Application;

namespace Suruga.DSharpPlus.Migrations
{
    [DbContext(typeof(DatabaseHandler))]
    [Migration("20210830163623_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.7.21378.4");

            modelBuilder.Entity("Suruga.Models.Startup", b =>
                {
                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Startup");
                });
#pragma warning restore 612, 618
        }
    }
}
